const CountryDescriptions = {
  CM: "Le Cameroun (aussi appelé l'Afrique en miniature) est un pays d'Afrique centrale, riche en biodiversité et en cultures variées. Sa capitale est Yaoundé.",
  MG: "Le Madagascar est une grande île située dans l'océan Indien, connue pour sa biodiversité unique et ses paysages variés. Sa capitale est Antananarivo.",
  AO: "L'Angola est un pays d'Afrique australe bordé par l'océan Atlantique. Il possède d'importantes ressources pétrolières et minières. Sa capitale est Luanda.",
  BF: "Le Burkina Faso est un pays d'Afrique de l'Ouest, connu pour sa diversité culturelle et ses festivals artistiques. Sa capitale est Ouagadougou.",
  BI: "Le Burundi est un petit pays d'Afrique de l'Est, caractérisé par ses collines verdoyantes et sa culture du café. Sa capitale est Gitega.",
  BJ: "Le Bénin est un pays d'Afrique de l'Ouest, riche en histoire avec l'ancien royaume du Dahomey. Sa capitale est Porto-Novo.",
  BW: "Le Botswana est un pays d'Afrique australe, connu pour ses réserves naturelles et le delta de l'Okavango. Sa capitale est Gaborone.",
  CD: "La République démocratique du Congo est un vaste pays d'Afrique centrale, doté d'immenses ressources naturelles. Sa capitale est Kinshasa.",
  CF: "La République centrafricaine est un pays enclavé d'Afrique centrale, riche en diamants. Sa capitale est Bangui.",
  CG: "La République du Congo est un pays d'Afrique centrale bordant l'océan Atlantique. Sa capitale est Brazzaville.",
  CI: "La Côte d'Ivoire est un pays d'Afrique de l'Ouest, premier producteur mondial de cacao. Sa capitale est Yamoussoukro.",
  DJ: "Djibouti est un petit pays de la Corne de l'Afrique, stratégiquement situé sur le détroit de Bab-el-Mandeb. Sa capitale est Djibouti.",
  DZ: "L'Algérie est le plus grand pays d'Afrique, caractérisé par son désert du Sahara et sa côte méditerranéenne. Sa capitale est Alger.",
  EG: "L'Égypte est un pays transcontinental, berceau d'une des plus anciennes civilisations. Sa capitale est Le Caire.",
  ER: "L'Érythrée est un pays de la Corne de l'Afrique bordant la mer Rouge. Sa capitale est Asmara.",
  ET: "L'Éthiopie est un pays de la Corne de l'Afrique, riche en histoire et berceau du café. Sa capitale est Addis-Abeba.",
  GA: "Le Gabon est un pays d'Afrique centrale couvert à 85% de forêts tropicales. Sa capitale est Libreville.",
  GH: "Le Ghana est un pays d'Afrique de l'Ouest, premier producteur mondial d'or du continent. Sa capitale est Accra.",
  GM: "La Gambie est le plus petit pays d'Afrique continentale, traversé par le fleuve Gambie. Sa capitale est Banjul.",
  GN: "La Guinée est un pays d'Afrique de l'Ouest, riche en ressources minières. Sa capitale est Conakry.",
  GQ: "La Guinée équatoriale est un pays d'Afrique centrale, composé d'une partie continentale et insulaire. Sa capitale est Malabo.",
  GW: "La Guinée-Bissau est un petit pays d'Afrique de l'Ouest, avec de nombreuses îles côtières. Sa capitale est Bissau.",
  KE: "Le Kenya est un pays d'Afrique de l'Est, célèbre pour ses parcs nationaux et sa faune sauvage. Sa capitale est Nairobi.",
  LR: "Le Libéria est un pays d'Afrique de l'Ouest, fondé par d'anciens esclaves américains. Sa capitale est Monrovia.",
  LS: "Le Lesotho est un royaume enclavé dans l'Afrique du Sud, connu pour ses montagnes. Sa capitale est Maseru.",
  LY: "La Libye est un pays d'Afrique du Nord, largement désertique avec une longue côte méditerranéenne. Sa capitale est Tripoli.",
  MA: "Le Maroc est un pays d'Afrique du Nord, riche en histoire et culture berbère et arabe. Sa capitale est Rabat.",
  ML: "Le Mali est un vaste pays sahélien d'Afrique de l'Ouest, héritier d'empires médiévaux prestigieux. Sa capitale est Bamako.",
  MR: "La Mauritanie est un pays d'Afrique de l'Ouest, largement couvert par le désert du Sahara. Sa capitale est Nouakchott.",
  MW: "Le Malawi est un pays d'Afrique australe, dominé par le lac Malawi. Sa capitale est Lilongwe.",
  MZ: "Le Mozambique est un pays d'Afrique australe bordé par l'océan Indien. Sa capitale est Maputo.",
  NA: "La Namibie est un pays d'Afrique australe, connu pour son désert du Namib et ses paysages spectaculaires. Sa capitale est Windhoek.",
  NE: "Le Niger est un pays sahélien d'Afrique de l'Ouest, largement désertique. Sa capitale est Niamey.",
  NG: "Le Nigeria est le pays le plus peuplé d'Afrique, riche en pétrole et en diversité culturelle. Sa capitale est Abuja.",
  RW: "Le Rwanda est un petit pays d'Afrique de l'Est, surnommé le pays des mille collines. Sa capitale est Kigali.",
  SD: "Le Soudan est un pays d'Afrique du Nord-Est, traversé par le Nil. Sa capitale est Khartoum.",
  SL: "La Sierra Leone est un pays d'Afrique de l'Ouest, connu pour ses plages et ses diamants. Sa capitale est Freetown.",
  SN: "Le Sénégal est un pays d'Afrique de l'Ouest, réputé pour sa culture et sa musique. Sa capitale est Dakar.",
  SO: "La Somalie est un pays de la Corne de l'Afrique, avec la plus longue côte d'Afrique continentale. Sa capitale est Mogadiscio.",
  SS: "Le Soudan du Sud est le plus jeune pays d'Afrique, indépendant depuis 2011. Sa capitale est Djouba.",
  SZ: "L'Eswatini (anciennement Swaziland) est une monarchie d'Afrique australe. Sa capitale est Mbabane.",
  TD: "Le Tchad est un pays d'Afrique centrale, caractérisé par le lac Tchad et le désert du Sahara. Sa capitale est N'Djamena.",
  TG: "Le Togo est un pays d'Afrique de l'Ouest, s'étirant comme un corridor vers le golfe de Guinée. Sa capitale est Lomé.",
  TN: "La Tunisie est un pays d'Afrique du Nord, connu pour ses sites archéologiques et ses plages méditerranéennes. Sa capitale est Tunis.",
  TZ: "La Tanzanie est un pays d'Afrique de l'Est, célèbre pour le Kilimandjaro et le Serengeti. Sa capitale est Dodoma.",
  UG: "L'Ouganda est un pays d'Afrique de l'Est, source du Nil et riche en faune sauvage. Sa capitale est Kampala.",
  ZA: "Le Sud-Africain est un pays d'Afrique australe, connu pour sa diversité culturelle et ses paysages variés. Sa capitale est Pretoria.",
  ZM: "Le Zambie est un pays d'Afrique australe, célèbre pour ses chutes Victoria et sa faune sauvage. Sa capitale est Lusaka.",
  ZW: "Le Zimbabwe est un pays d'Afrique australe, connu pour ses paysages variés et ses parcs nationaux. Sa capitale est Harare.",
};

export default CountryDescriptions;